services:
  myapp1:
    depends_on:
      db:
        condition: service_healthy
    build: ./app 
    image: myapp
    environment:
      DB_HOST: db
      DB_NAME: todo
      DB_USER: myuser
      DB_PASSWORD: pass
    networks:
    - front
    - back

  myapp2:
    depends_on:
      db:
        condition: service_healthy
    build: ./app 
    image: myapp
    environment:
      DB_HOST: db
      DB_NAME: todo
      DB_USER: myuser
      DB_PASSWORD: pass
    networks:
    - front
    - back

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
      MYSQL_USER: myuser
      MYSQL_PASSWORD: pass
    volumes:
    -  sql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - back

  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./nginx/default.conf:/etc/nginx/templates/default.conf.template
    depends_on:
    - myapp1
    - myapp2
    environment:
      APP_1_HOST: myapp1
      APP_2_HOST: myapp2
    networks:
    - front


volumes:
  sql_data:

networks:
  back:
  front:
